from django.db import models

# Create your models here.


# For any model there will be a primary key that will be created by the django ORM.
# it will be ID starts from 1 and increments .
class Position(models.Model):
    title = models.CharField(max_length=50)


class Employee(models.Model):
    fullname = models.CharField(max_length=100)
    emp_code = models.CharField(max_length=3)
    mobile = models.CharField(max_length=15)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)


# python manage.py makemigrations makes a 0001 file where it converts the models to corresponding python code.

# python manage.py sqlmigrate employee_register 0001 => running this gives the sql code to do the same modifications    
# BEGIN;
# --
# -- Create model Position
# --
# CREATE TABLE "employee_register_position" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(50) NOT NULL);
# --
# -- Create model Employee
# --
# CREATE TABLE "employee_register_employee" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "fullname" varchar(100) NOT NULL, "emp_code" varchar(3) NOT NULL, "mobile" varchar(15) NOT NULL, "position_id" bigint NOT NULL);
# ALTER TABLE "employee_register_employee" ADD CONSTRAINT "employee_register_em_position_id_c7c8c467_fk_employee_" FOREIGN KEY ("position_id") REFERENCES "employee_register_position" ("id") DEFERRABLE INITIALLY DEFERRED;
# CREATE INDEX "employee_register_employee_position_id_c7c8c467" ON "employee_register_employee" ("position_id");
# COMMIT;
